env:
  browser: true
  es6: true
  node: true

extends: 'eslint:recommended'

rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - 0
  no-multiple-empty-lines:
    - warn
  max-len:
    - 1
    - 100
  no-var:
    - 2
  prefer-const:
    - 2
    no-unused-vars:
    - 0
